name = "chess-connections-leaderboard"
main = "src/index.js"
compatibility_date = "2024-09-25"

# KV namespace for storing submissions. Created on first deploy —
# wrangler will print the binding to add here if it's missing.
[[kv_namespaces]]
binding = "LEADERBOARD"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
